import './globals.css'

export const metadata = {
  title: 'Template: Change Name',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body><nav><h1>My Navebar</h1></nav>
        
        {children}</body>
    </html>
  )
}
